server:
  port: 8084

spring:
  application:
    name: cloud-brain-ai-assistant
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_brain_ai_assistant
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: localhost:9092

ai:
  llm:
    url: http://cloud-brain-ai-llm/api/llm

management:
  endpoints:
    web:
      exposure:
        include: health
  tracing:
    sampling:
      probability: 1.0
