server:
  port: 8084

spring:
  application:
    name: cloud-brain-ai-assistant
  kafka:
    bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: health
  tracing:
    sampling:
      probability: 1.0
