server:
  port: 8087

spring:
  application:
    name: cloud-brain-patient
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_brain_patient?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: health
  tracing:
    sampling:
      probability: 1.0
