server:
  port: 8080

spring:
  application:
    name: cloud-brain-gateway
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

management:
  endpoints:
    web:
      exposure:
        include: health
  tracing:
    sampling:
      probability: 1.0
